<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
</body>
<form action="" method="post">
    <input type="submit" value="send" name="send">
</form>
<!-- <?php
// class Name{
// public $stud_num;
// public $stud_name;
// function printo(){
//     $num = $this-> stud_num;
//     $nam = $this-> stud_name;
//     echo "<h5>$num</h5> <h5>$nam</h5>";
// }
// }
// if(isset($_POST['send'])){
//     $all = new Name();
//     $all -> $stud_num =1;
//     $all -> $stud_name ='imane';
//     $all -> printo();
// }
?> -->
<!-- ////////////////////////////////////////////////// -->

<form method="POST">
    <input type="submit" value="connect" name="con">
    <center>
        <table border="2">

            <tr>
                <th>ID</th>
                <th>NAME</th>
                <th>ADRESS</th>
            </tr>


</html>